### ISSUE TITLE
Returns too many answers

### ISSUE THREAD

**Issue by Anco88** [DanielsWrath/LanguagePractical#1]
With question Wie is de coach van Sven Kramer? it returns: ['http://nl.dbpedia.org/resource/Jac_Orie']  ['Jac Orie']    

Also both answers are a list with a string

**Comment by DanielHaitink** [comment]
Dat is correct, we hebben de URI en de naam nodig om te checken of het een persoon/locatie o.i.d. is 

Uiteindelijke antwoord is`1    Jac Orie`
