### ISSUE TITLE
Geboorteplaats URI heeft geen type, dus wordt niet herkend

### ISSUE THREAD

**Issue by DanielHaitink** [DanielsWrath/LanguagePractical#11]
`Waar is Usain Bolt geboren ?`
Gaat fout omdat de plaats URI geen Location, Town, Country o.i.d. is volgens DBPedia
` geboorteplaats

```
SELECT ?answer

WHERE{
<http://nl.dbpedia.org/resource/Usain_Bolt> prop-nl:geboorteplaats ?answer
}
```

['http://nl.dbpedia.org/resource/Trelawny', 'http://nl.dbpedia.org/resource/Sherwood_Content']
location
url: http://nl.dbpedia.org/resource/Trelawny
['http://nl.dbpedia.org/resource/Trelawny']
[]
url: http://nl.dbpedia.org/resource/Sherwood_Content
['http://nl.dbpedia.org/resource/Sherwood_Content']
[] `

**Comment by Anco88** [comment]
property inwoners is nu genoeg om aan te nemen dat URI een locatie is
