### ISSUE TITLE
Voeg alle Olympic en Athlete properties en synoniemen handmatig toe!

### ISSUE THREAD

**Issue by DanielHaitink** [DanielsWrath/LanguagePractical#12]
We moeten (met name de meest voorkomende) HANDMATIG in de synoniemen (misschien ook nog wel een extra corpus achtig bestand) toevoegen zodat hij vrijwel gegarandeerd het vindt.

**Comment by DanielsWrath** [comment]
@jwdw Test

**Comment by DanielHaitink** [comment]
Zie bestand `Resources/OlympicProps.txt`

**Comment by DanielHaitink** [comment]
Door bestand heen gebladerd en enkele synonyms toegevoegd!
