### ISSUE TITLE
Hebben en Zijn eruit filteren

### ISSUE THREAD

**Issue by DanielHaitink** [DanielsWrath/LanguagePractical#13]
Bij properties werkwoorden als Hebben en Zijn eruit filteren om te zorgen dat we geen rare synoniemen krijgen

**Comment by Anco88** [comment]
Hebben bij parseverbs eruit gefilterd (als goed is, nu aan het testen)
Zijn wat lastiger, omdat goede woord gepakt moet worden(wat niet een ww is)
