### ISSUE TITLE
Test of mappen met bestanden en check werkt op windows 

### ISSUE THREAD

**Issue by DanielHaitink** [DanielsWrath/LanguagePractical#14]

**Comment by Anco88** [comment]
Wat word precies bedoelt met test of mappen met bestanden?
Momenteel werkt het op windows (moet ik helaas toegeven, aangezien dact niet op ubuntu 15.10 werkt...) na kleine aanpassing

**Comment by DanielHaitink** [comment]
Ik wist niet zeker of hij bij de resource bestanden kon, maar blijkbaar dus wel
