### ISSUE TITLE
Eerst zoeken naar breder concept (Olympische spelen + sport)?

### ISSUE THREAD

**Issue by DanielHaitink** [DanielsWrath/LanguagePractical#15]
Misschien is het handig om te kijken of in de zin ook een sport genoemd wordt en je daar dan eerst tot te beperken, nu vind hij OF de sport OF de olympische zomer/winterspelen xxxx.

**Comment by DanielHaitink** [comment]
https://nl.wikipedia.org/wiki/Olympische_sport?wprov=sfla1

**Comment by Anco88** [comment]
Voor parsenumber of heb ik nu:
    concepts = xml.xpath('//node[@rel="body" and ../@cat="whq"]')

```
for name in concepts:
    c =getTreeWordList(name,v.TYPE_WORD, exclude = [['pos','verb']])
```

waarbij die hele body pakt, behalve werkwoorden, weet niet of voor andere dingen ook handig kan zijn

**Comment by DanielHaitink** [comment]
Lijkt te werken!
