### ISSUE TITLE
Teveel toegevoegd aan concept

### ISSUE THREAD

**Issue by Anco88** [DanielsWrath/LanguagePractical#16]
Bij vraag: Hoeveel deelnemende atleten waren er op de Olympische Spelen van 1896?
pakt hij "er op de Olympische spelen van 1896" als concept

Bij: Hoeveel fakkelsdragers waren er bij de spelen van 2012?
Pakt hij alleen "er"

**Comment by DanielHaitink** [comment]
lijkt opgelost door @jwdw difflib functie
