### ISSUE TITLE
Vragen die beginnen met "door wie" werken niet

### ISSUE THREAD

**Issue by jwdw** [DanielsWrath/LanguagePractical#18]
Voorbeeld: Door wie werden de Olympische Spelen van 2004 geopend? 

Krijgt geen expected answer en wordt niet doorgestuurt naar questionParser

**Comment by jwdw** [comment]
Werkt nu, wordt doorgestuurd naar parseVerbs. not (@lemma="worden") toegevoegd net als bij "hebben", zodat ie dat niet als property pakt

**Comment by DanielHaitink** [comment]
Heeft hij nu wel een expected answer?

**Comment by jwdw** [comment]
Ja, die wordt later geassigned bij al die if checks, zie regel 89 van prePostParser

**Comment by DanielHaitink** [comment]
Je moet gewoon bij variables WHD_PERSON gewoon "door wie" Toevoegen.
Daarnaast ff checks maken voordat je kijkt in de array locations

**Comment by jwdw** [comment]
oja dat is slim, heb ik gedaan
