### ISSUE TITLE
Olympische zomerspelen geeft olympische zomerspelen 2012 als concept

### ISSUE THREAD

**Issue by Anco88** [DanielsWrath/LanguagePractical#19]
Zie titel.
zomerspelen 2012 heeft meer links erna toe.

In dit geval zou optie kunnen zijn door meerdere concepts (gesorteerd) terug te geven en naar volgende concept te springen als properties niet genoeg overeenkomen. (werkt in dit geval omdat olympische zomerspelen 2012 geen property eerste heeft en olympische zomerspelen wel.
Hoewel vraag is of dit bij meerderheid foute concepts werkt.

**Comment by DanielHaitink** [comment]
Maar waarom zoe je alleen Olympische Zomerspelen geven? Er staat toch altijd wel een jaartal achter?

**Comment by jwdw** [comment]
Ligt aan pairCounts, dus daar kunnen we niet zoveel aan doen. Denk niet dat we meer vragen goed gaan hebben als we door meerdere concepts gaan zoeken
