### ISSUE TITLE
Leeftijd toevoegen?

### ISSUE THREAD

**Issue by DanielHaitink** [DanielsWrath/LanguagePractical#23]
Bij de vragen:
`Hoe oud is X` en `Wat is de leeftijd van X` vind hij of lengte of niks omdat dbPedia niet aan leeftijd doet
Misschien huidige datum -  geboorte datum doen??

**Comment by Anco88** [comment]
als property oud of leeftijd is, gaat die nu naar parseTimeDifference toe, welke verschil in jaren geeft
