### ISSUE TITLE
Pakt bijvoeglijk naamwoord van property niet

### ISSUE THREAD

**Issue by DanielHaitink** [DanielsWrath/LanguagePractical#24]
`Hoeveel bronzen medailles heeft Nederland op de Olympische Zomerspelen 2008 ?`
Heeft de juiste concept maar `medailles` als property, niet bronzen medaille
`Hoeveel bronzen medailles heeft Nederland op de Olympische Zomerspelen 2008 gewonnen ?`
Heeft alleen Nederland als property niet `Nederland op de Olympische Zomerspelen 2008`

**Comment by jwdw** [comment]
hij pakt nu ook het adjective als property, en als hij wel een concept vind maar geen URI probeert hij  nu met de difflib manier om alsnog een URI te vinden
