### ISSUE TITLE
URI niet gevonden

### ISSUE THREAD

**Issue by DanielHaitink** [DanielsWrath/LanguagePractical#5]
Bij de vraag:
`Waar is het hoofdkantoor van Apple?`
Zoekt hij op een URI voor `het hoofdkantoor van Apple` i.p.v. `Apple`

**Comment by Anco88** [comment]
Probleem is met vraag: Waar waren de Olympische spelen van 2012? Wil je wel hele deel hebben.
Hij probeert nu beide om url te vinden. Eerst de langste want die is meest specifiek, daarna object van zin. Lijkt redelijk te werken

**Comment by DanielHaitink** [comment]
Prima, lijkt me opgelost dan
