### ISSUE TITLE
Property niet gevonden door lidwoord weg te laten

### ISSUE THREAD

**Issue by DanielHaitink** [DanielsWrath/LanguagePractical#6]
Bij de zin:
`Wie is lid van Coldplay?` gaat fout in parseXofY geloof ik.
`Wie zijn de leden van Coldplay?` Werkt echter wel
`Wie is het lid van Coldplay?` wekt ook

**Comment by Anco88** [comment]
xpath voor property en concept wat ruimer gemaakt, pakt dit nu goed op
