### ISSUE TITLE
Foute property bij waar wanneer vragen

### ISSUE THREAD

**Issue by Anco88** [DanielsWrath/LanguagePractical#7]
Bij: 
Wanneer waren de Zomerspelen van 2012? 
Geeft die "zijn" als property

**Comment by DanielHaitink** [comment]
Komt omdat je de verbs pakt geloof ik en niet filtert. Je moet de Lemma's pakken en Zijn en Hebben enzo eruit filteren. Probleem is dat de dan geen property hebt in deze gevallen
Je kan smerig doen en wanneer waar enzo hard linken aan sommige properties
