### ISSUE TITLE
Andersom vragen wordt te vroeg en niet correct gebruikt

### ISSUE THREAD

**Issue by DanielHaitink** [DanielsWrath/LanguagePractical#8]
Bij de volgende vragen kon hij wel een antwoord vinden maar dat duurde even, nu gaat hij in andersom vragen en geeft een fout antwoord
`Wie is de koning van Nederland?`
`Wie is de president van Amerika?`
Waarschijnlijk nog wel meer vragen

**Comment by Anco88** [comment]
Voor koning staat er geen synoniem van staatshoofd bij. Wat mij meer het probleem lijkt.
En president heeft geen synoniem van regeringsleider

Als je ze pas na de gewone vragen doet is probleem dat ze pas te laat opgepakt worden en dus bij andersomvragen fouten gaat maken.

**Comment by Anco88** [comment]
Synoniemen voor koning en president toevoegen lost dit probleem ook op, en vind ze zelfs zeer snel. 
Lijkt me betere oplossing (hoewel er waarschijnlijk meer synoniemen toegevoegd moeten worden)

**Comment by DanielHaitink** [comment]
Dan zullen we, ben ik bang, een grote lijst van woorden aan de synoniemen lijst moeten toevoegen, helemaal gericht op de olympische spelen. 
Handigste is om alle properties van olympische pagina's te pakken en te checken of we die kunnen vinden
